---  
- name: Set hostname to fqdn variable
  hostname: name={{ fqdn }}

- name: Set hostname in /etc/hosts
  lineinfile: line="127.0.1.1 {{ fqdn }}" dest=/etc/hosts state=present backup=yes 

- name: Install prereq packages
  apt: update_cache=yes pkg={{ item }} state=present
  with_items:
   - python-pycurl
   - git
   - curl

- name: Add resourcemap apt key
  apt_key: url=http://apt.instedd.org/gpg.key state=present

- name: Add resoucemap repo
  apt_repository: repo='deb http://apt.instedd.org/ instedd main' state=present update_cache=yes

- name: Install resourcemap
  apt: pkg=resourcemap state=present

- name: Insert settings.yml
  template: src=settings.yml dest=/etc/resourcemap/settings.yml owner=root group=resourcemap mode=0644
